WebQuanAn/Areas/Admin/Controllers/CategoryController.cs
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.DataAcess.Data;
using WebQuanAn.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebQuanAn.Utility;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace WebQuanAn.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly INotyfService _notyf;
        public CategoryController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment, INotyfService notyf)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
            _notyf = notyf;
        }
        public async Task<IActionResult> Index()
        {
            List<Category> objCategoryList = _unitOfWork.Category.GetAll().ToList();
            return View(objCategoryList);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category category,IFormFile? file)
        {

            if (!ModelState.IsValid)
            {
               return View(category);
            }
            string wwwroot = _webHostEnvironment.WebRootPath;
            if(file != null)
            {
                string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string categoryPath = Path.Combine(wwwroot, @"images\categories");
                using ( var fileStream = new FileStream(Path.Combine(categoryPath, filename), FileMode.Create)){
                    file.CopyTo(fileStream);
                }
                category.ImageUrl = @"\images\categories\" + filename;
            }
            _unitOfWork.Category.Add(category);
            _unitOfWork.Save();
            _notyf.Success("Tạp danh mục thành công");
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryDb = _unitOfWork.Category.Get(u => u.Id == id);      
            if (categoryDb == null)
            {
                return NotFound();
            }
            return View(categoryDb);
        }
        [HttpPost]
        public IActionResult Edit(Category category, IFormFile? file)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            string wwwroot = _webHostEnvironment.WebRootPath;
            if (file != null)
            {
                string filename = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string categoryPath = Path.Combine(wwwroot, @"images\categories");
                if(!string.IsNullOrEmpty(category.ImageUrl))
                {
                    var oldPath = Path.Combine(wwwroot, category.ImageUrl.TrimStart('\\'));  
                    if(System.IO.File.Exists(oldPath))
                    {
                        System.IO.File.Delete(oldPath);
                    }
                }
                using (var fileStream = new FileStream(Path.Combine(categoryPath, filename), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                category.ImageUrl = @"\images\categories\" + filename;
            }
            _unitOfWork.Category.Update(category);
            _unitOfWork.Save();
            _notyf.Success("Cập nhật danh mục thành công");
            return View(nameof(Index));
        }
        #region API CALL
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Category> categories = _unitOfWork.Category.GetAll().ToList();
            return Json(new {data = categories});
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var cateogry = _unitOfWork.Category.Get(x=>x.Id == id);
            _unitOfWork.Category.Remove(cateogry);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Xoá danh mục thành công!" });
        }
        #endregion
    }
}

WebQuanAn/Controllers/CategoryController.cs
using WebQuanAn.Models.ViewModels;
using WebQuanAn.Models;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using AspNetCoreHero.ToastNotification.Abstractions;
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.Utility;

namespace WebSoccer.Controllers
{
	public class CategoryController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly INotyfService _notyf;
		private int PageSize = SD.PageSize;
		public CategoryController(IUnitOfWork unitofwork, INotyfService notyf)
		{
			_unitOfWork = unitofwork;
			_notyf = notyf;
		}
		[HttpGet]
		public IActionResult Index(int categoryId, int productpage = 1)
		{
			IEnumerable<Category> categories = _unitOfWork.Category.GetAll().ToList();
			IEnumerable<Product> products = _unitOfWork.Product.GetAll(x => x.CategoryId == categoryId, includeProperties: "Category,ProductImages")
							.Skip((productpage - 1) * PageSize)
							.Take(PageSize)
							.ToList();

			ProductCategoryVM productVM = new()
			{
				Products = products,
				Categories = categories,
				PageInfo = new PageInfo()
				{
					TotalItems = _unitOfWork.Product.GetAll(x => x.CategoryId == categoryId, includeProperties: "Category,ProductImages").Count(),
					ItemsPerPage = PageSize,
					CurrentPage = productpage,
				}
			};
			ViewBag.CategoryId = categoryId;
			ViewBag.Category = _unitOfWork.Category.Get(x => x.Id == categoryId).Name;
			return View(productVM);
		}

		[HttpPost]
		public IActionResult GetFilters(int categoryId,string sort)
		{
			var categories = _unitOfWork.Category.GetAll().ToList();
			var products = _unitOfWork.Product.GetAll(x => x.CategoryId == categoryId, includeProperties: "Category,ProductImages");
		
			switch (sort)
			{
				case "lowtohigh":
					{
						products = products.OrderBy(x => x.Price).ToList();
						break;
					}
				case "hightolow":
					{
						products = products.OrderByDescending(x => x.Price).ToList();
						break;
					}
				case "az":
					{
						products = products.OrderBy(x => x.Name).ToList();
						break;
					}
				default:
					{
						products = products.ToList();
						break;
					}
			}
			return PartialView("_ProductList", products);
		}
	}
}

WebQuanAn/Controllers/ProductController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using WebQuanAn.DataAccess.Repository;
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.Models;
using WebQuanAn.Models.ViewModels;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;
using Microsoft.AspNetCore.Http;
using WebQuanAn.Utility.Helpers;
using Microsoft.CodeAnalysis.Options;
using Newtonsoft.Json.Linq;
using Microsoft.CodeAnalysis;
using WebQuanAn.Utility;

namespace WebQuanAn.Controllers
{
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly INotyfService _notyf;
        private int PageSize = SD.PageSize;
        public ProductController(IUnitOfWork unitofwork, INotyfService notyf)
        {
            _unitOfWork = unitofwork;
            _notyf = notyf;
        }
        public IActionResult Index(int productpage = 1)
        {
            var categories = _unitOfWork.Category.GetAll().ToList();
            var products = _unitOfWork.Product.GetAll(includeProperties: "Category,ProductImages")
                            .Skip((productpage - 1) * PageSize)
                            .Take(PageSize)
                            .ToList();
            ProductCategoryVM productVM = new()
            {
                Products = products,
                Categories = categories,
                PageInfo = new PageInfo()
                {
                    TotalItems = _unitOfWork.Product.GetAll().Count(),
                    ItemsPerPage = PageSize,
                    CurrentPage = productpage,
                }
            };
            return View(productVM);
        }

		[HttpPost]
		public IActionResult GetFilters(string sort)
		{
			var categories = _unitOfWork.Category.GetAll().ToList();
			var products = _unitOfWork.Product.GetAll(includeProperties: "Category,ProductImages");
			switch (sort)
			{
				case "lowtohigh":
					{
						products = products.OrderBy(x => x.Price).ToList();
						break;
					}
				case "hightolow":
					{
						products = products.OrderByDescending(x => x.Price).ToList();
						break;
					}
				case "az":
					{
						products = products.OrderBy(x => x.Name).ToList();
						break;
					}
                default:
                {
                    products = products.ToList();
					break;
                }
				
			}	
			return PartialView("_ProductList", products);
		}
		[HttpGet]
        public IActionResult Details(int productId)
        {
            ShoppingCart cart = new()
            {
                Product = _unitOfWork.Product.Get(u => u.Id == productId, includeProperties: "Category,ProductImages"),
                Quantity = 1,
                ProductId = productId
            };
            var comment = _unitOfWork.Comment.GetAll(x=>x.ProductId == productId).ToList();
            var productDetails = new ProductDetailVM()
            {
                ShoppingCart = cart,            
                Comments = comment
            };
			return View(productDetails);
        }


        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            ShoppingCart cart = new ShoppingCart()
            {
                ProductId = productId,
                Quantity = quantity,
            };
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = Guid.Parse(claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value);
            cart.ApplicationUserId = userId;
            var cartDb = _unitOfWork.ShoppingCart.Get(x => x.ApplicationUserId == userId
                                                        && x.ProductId == cart.ProductId);
            int currentCartQuantity = 0;
            if (cartDb != null)
            {
                cartDb.Quantity += cart.Quantity;
                _unitOfWork.ShoppingCart.Update(cartDb);
				_unitOfWork.Save();
                HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == userId).Count());
            }
            else
            { 
                _unitOfWork.ShoppingCart.Add(cart);
				_unitOfWork.Save();
                currentCartQuantity = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == userId).Count();
                HttpContext.Session.SetInt32(SD.SessionCart, currentCartQuantity);
            }
			return Redirect(Request.Headers["Referer"].ToString());
		}
		[HttpPost]
		public IActionResult AddToWish(int productId, int quantity)
		{
			var product = _unitOfWork.Product.Get(x => x.Id == productId);
			if (product == null)
			{
				return NotFound();
			}

			if (HttpContext.Session.Get<List<CartItemVM>>("GioHang") == null)
			{
				List<CartItemVM> carts = new List<CartItemVM>();
				carts.Add(new CartItemVM()
				{
					Product = product,
					Quantity = quantity,	
				});
				HttpContext.Session.Set("GioHang", carts);
			}
			else
			{
				List<CartItemVM> carts = HttpContext.Session.Get<List<CartItemVM>>("GioHang");
				int index = FindCartItemIndex(productId, carts);
				if (index == -1)
				{
					carts.Add(new CartItemVM()
					{
						Product = product,
						Quantity = quantity,
					});
				}
				else
				{
					carts[index].Quantity += quantity;
				}
				HttpContext.Session.Set("GioHang", carts);
			}

			return Redirect(Request.Headers["Referer"].ToString());
		}

		private int FindCartItemIndex(int productId, List<CartItemVM> carts)
		{
			for (var i = 0; i < carts.Count; i++)
			{
				if (carts[i].Product.Id == productId)
				{
					return i;
				}
			}
			return -1;
		}

		[HttpPost]
        public IActionResult AddComment(int productId, string text, int rating =1 )
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = Guid.Parse(claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value);
            var user = _unitOfWork.ApplicationUser.Get(x=>x.Id== userId);   
            if(!ModelState.IsValid) { return View(); }
            var newcomment = new Comment()
            {
                ApplicationUserId = userId,
                Text = text,
                ProductId = productId,
                Name = user.LastName,
                Rating = rating,
            };
            _unitOfWork.Comment.Add(newcomment);
            _unitOfWork.Save();
            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

WebQuanAn/Controllers/ViewComponents/GetCategoryViewComponent.cs
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.Models;
using WebQuanAn.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebQuanAn.ViewComponents
{
    public class GetCategoryViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public GetCategoryViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = _unitOfWork.Category.GetAll();
            return View(categories);
        }
    }
}

WebQuanAn/Views/Category/Index.cshtml
@using WebQuanAn.Utility.Helpers;
@model ProductCategoryVM
@{
    Layout = "_LayoutProduct";
}
<style>
    .bg-top {
        padding-top: 20px;
        padding-bottom: 20px;
    }
    #mySelect {
        padding: 8px;
        border: 1px solid #ccc;
        border-radius: 4px;
        font-size: 14px;
        color: #333;
        background-color: #fff;
        width: 200px;
    }
    /* Tùy chỉnh option */
    #mySelect option {
        font-size: 14px;
        color: #333;
        background-color: #fff;
    }

    .col-md-12.pagination {
        display: flex;
        justify-content: center;
    }
</style>
<!-- breadcrumbs area start -->
<div class="breadcrumbs_aree breadcrumbs_bg mb-110" data-bgimg="/client-site/assets/img/others/breadcrumbs-bg.png">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="bg-top breadcrumbs_text">
                    <h1>Thực đơn</h1>
                    <ul>
                        <li><a asp-action="Index" asp-controller="Home">Trang chủ </a></li>
                        <li><a asp-action="Index" asp-controller="Product">// Thực đơn </a></li>
                        <li> // @ViewBag.Category</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumbs area end -->
<!-- product page section start -->
<div class="product_page_section mb-100">
    <div class="container">
        <div class="product_header">
            <div class="section_title text-center">
                <div>
                    <img src="~/client-site/assets/img/logo/logo.png" />
                </div>
            </div>
            <div class="product_tab_button">
                <ul class="nav justify-content-center">                                 
                    @await Component.InvokeAsync("GetCategory") 
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 order-1 order-lg-2">
                <div class="product_page_wrapper">
                    <div class="product_sidebar_header d-flex justify-content-between align-items-center">
                        <div class="product_header_right d-flex align-items-center">
                            <strong>Sắp xếp:</strong>
                            <select id="mySelect">
                                <option value="all">Mặc định</option>
                                <option value="lowtohigh">Từ thấp đến cao</option>
                                <option value="hightolow">Từ cao đến thấp</option>
                                <option value="az ">Từ A-Z</option>
                            </select>
                            <input id="cateId" value="@ViewBag.CategoryId" hidden />
                        </div>
                    </div>
                    <!--shop toolbar area end-->
                    <!--shop gallery start-->
                    <div class="product_page_gallery mt-3">
                        <div id="productContainer">      
                            <div class="row grid__product">
								@foreach (var item in Model.Products)
								{
                                    <div class="total-item col-lg-4 col-md-4 col-sm-6">
                                        <div class="product_thumb">
                                                    @if (item.ProductImages != null && item.ProductImages.Count() > 0)
                                                    {
                                                        <a asp-action="Details" asp-controller="Product" asp-route-productId="@item.Id"><img src="@item.ProductImages.FirstOrDefault().ImageUrl" class="card-img-top rounded" style="width:100px height:100px"/></a>
                                                    }
                                                    else
                                                    {
                                                        <a asp-action="Details" asp-controller="Product" asp-route-productId="@item.Id"><img src="https://placehold.co/500x600/png" class="card-img-top rounded" /></a>
                                                    }
                                                    <div class="action_links">
                                                        <ul class="d-flex justify-content-center">
                                                            <li class="add_to_cart">
                                                                <a href="cart.html"
                                                                    title="Thêm vào giỏ hàng">
                                                                    <span class="pe-7s-shopbag"></span>
                                                                </a>
                                                            </li>
                                                            <li class="wishlist">
                                                                <a href="#"
                                                                    title="Yêu thích">
                                                                    <span class="pe-7s-like"></span>
                                                                </a>
                                                            </li>
                                                            <li class="quick_button">
                                                                <a href="#" title="Quick View"
                                                                    data-bs-toggle="modal"
                                                                    data-bs-target="#modal_box">
                                                                    <span class="pe-7s-look"></span>
                                                                </a>
                                                            </li>
                                                        </ul>
                                                    </div>
                                                </div>
                                        <figcaption class="product_content text-center">
                                            <h4>@item.Name</h4>
                                            <div class="price_box">
                                                <span class="current_price">@item.Price.ToVnd()</span>
                                            </div>
                                        </figcaption>                              
                                    </div>
                                }                                   
                            </div>
             
                            <div class="row">
                                <div class="col-md-12 pagination">
                                    <div class="block-27">
                                        <ul>
                                            @for (int i = 1; i <= Model.PageInfo.TotalPages; i++)
                                            {
                                                <li><a href="/Category?categoryId=@ViewBag.CategoryId&productpage=@i">@i</a></li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
	<script>
		var categoryId;
		document.getElementById("mySelect").addEventListener("change", function () {
			var selectedOption = this.value;
			// Thực hiện hành động dựa trên selectedOption
			console.log("Option được chọn: " + selectedOption);
			categoryId = $("#cateId").val();	
			$.ajax({
				url: "/Category/GetFilters",
				type: 'post',
				data: {
					sort: selectedOption,
					categoryId: categoryId
				},
				success: function (data) {
					$('#productContainer').html(data);
                    var totalItem = document.querySelectorAll(".total-item");
					var pageSize = @SD.PageSize;
					var totalPage = Math.ceil(totalItem.length / pageSize);
					const div1 = document.createElement("div");
					div1.classList.add("row");
					const div2 = document.createElement("div");
                    div2.classList.add("col-md-12", "pagination");
					const div3 = document.createElement("div");
					div3.classList.add("block-27");
					const ul = document.createElement("ul");
					for (i = 1; i <= totalPage; i++) {
						var li = document.createElement("li");
						var a = document.createElement("a");
						a.innerHTML = i;
						a.addEventListener('click', handlePageClick);
						a.href = "/Category?categoryId=" + categoryId + "&productpage=" + i;
						li.appendChild(a);
						ul.appendChild(li);
					}
					div3.appendChild(ul);
					div2.appendChild(div3);
					div1.appendChild(div2);
					document.getElementById("productContainer").appendChild(div1);
					ShowPage(categoryId, 1);
				},
				error: function () {
					console.log("Lỗi");
				}
			});
		});
		function handlePageClick(event) {
			event.preventDefault();
			var pageNumber = parseInt(event.target.textContent);
			event.target.style.cursor = 'pointer';
			ShowPage(categoryId,pageNumber);
		}
		function ShowPage(categoryId, pageNumber) {
            var totalItems = document.querySelectorAll(".total-item");
			var pageSize = @SD.PageSize;
			var startIndex = (pageNumber - 1) * pageSize;
			var endIndex = startIndex + pageSize;
			for (i = 0; i < totalItems.length; i++) {
				if (i >= startIndex && i < endIndex) {
					totalItems[i].style.display = "block";
				} else {
					totalItems[i].style.display = "none";
				}
			}
		}
	</script>
} 