WebQuanAn/Areas/Admin/Controllers/DashboardController.cs
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.Utility;
using WebQuanAn.Utility.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebQuanAn.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DashboardController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;

        public DashboardController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
		{
            var orderheaders = _unitOfWork.OrderHeader.GetAll().Where(x=>x.OrderStatus == SD.StatusShipped);
            double total = 0;
            foreach(var order in orderheaders) {
                total += order.OrderTotal;
            }
            var totalusers = _unitOfWork.ApplicationUser.GetAll().Count();
            var productsold = _unitOfWork.OrderDetail.GetAll();
            int totalProducts = 0;
            foreach (var order in productsold)
            {
                totalProducts += order.Count;
            }
            var orderheader = _unitOfWork.OrderHeader.GetAll().Count();
            ViewBag.TotalOrder = orderheader;
            ViewBag.Total = total.ToVnd();
            ViewBag.TotalUsers = totalusers;
            ViewBag.Products = totalProducts;
			return View();
		}
	}
}

WebQuanAn/Areas/Admin/Controllers/UserController.cs
using WebQuanAn.DataAccess.Repository;
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.DataAcess.Data;
using WebQuanAn.Models;
using WebQuanAn.Models.ViewModels;
using WebQuanAn.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebQuanAn.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UserController : Controller
    { 
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        public UserController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IUnitOfWork unitOfWork)
        {
            _context = context;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {

            return View();
        }
        [HttpGet]
        public IActionResult RoleManagement(Guid userId)
        {

            RoleManagementVM roleVM = new RoleManagementVM()
            {
                ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId),
                RoleList = _context.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                })
            };
            roleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == userId))
                    .GetAwaiter().GetResult().FirstOrDefault();
            return View(roleVM);
        }
        [HttpPost]
        public IActionResult RoleManagement(RoleManagementVM roleVM)
        {
            string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == roleVM.ApplicationUser.Id))
                    .GetAwaiter().GetResult().FirstOrDefault();
            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == roleVM.ApplicationUser.Id);
            if (!(roleVM.ApplicationUser.Role == oldRole))
            {
                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(applicationUser, roleVM.ApplicationUser.Role).GetAwaiter().GetResult();
            }
            else
            {
                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
            }
            return RedirectToAction("Index");
        }
    
        #region API CALLS
        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> users = _context.ApplicationUsers.ToList();
            var userRoles = _context.UserRoles.ToList();
            var roles = _context.Roles.ToList();
            foreach(var user in users)
            {
                var roleId = userRoles.FirstOrDefault(x => x.UserId == user.Id).RoleId;
                user.Role = roles.FirstOrDefault(x => x.Id == roleId).Name;
            }
            return Json(new {data = users});
        }
        [HttpPost]
        public IActionResult LockUnlock([FromBody] Guid id)
        {
            var user = _context.ApplicationUsers.FirstOrDefault(x => x.Id == id);
            if(user == null)
            {
                return Json(new { suceess = false, message = "Lỗi khi khoá/mở tài khoản" });
            }
            if(user.LockoutEnd!=null && user.LockoutEnd > DateTime.Now)
            {
                user.LockoutEnd = DateTime.Now;
            }
            else
            {
                user.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _context.SaveChanges();
            return Json(new { success = true, message = "Thành công!" });
        }


        #endregion
    }
}

WebQuanAn/Controllers/CategoryController.cs
using WebQuanAn.Models.ViewModels;
using WebQuanAn.Models;
using Microsoft.AspNetCore.Mvc;
using System.Drawing.Printing;
using AspNetCoreHero.ToastNotification.Abstractions;
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.Utility;

namespace WebSoccer.Controllers
{
	public class CategoryController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly INotyfService _notyf;
		private int PageSize = SD.PageSize;
		public CategoryController(IUnitOfWork unitofwork, INotyfService notyf)
		{
			_unitOfWork = unitofwork;
			_notyf = notyf;
		}
		[HttpGet]
		public IActionResult Index(int categoryId, int productpage = 1)
		{
			IEnumerable<Category> categories = _unitOfWork.Category.GetAll().ToList();
			IEnumerable<Product> products = _unitOfWork.Product.GetAll(x => x.CategoryId == categoryId, includeProperties: "Category,ProductImages")
							.Skip((productpage - 1) * PageSize)
							.Take(PageSize)
							.ToList();

			ProductCategoryVM productVM = new()
			{
				Products = products,
				Categories = categories,
				PageInfo = new PageInfo()
				{
					TotalItems = _unitOfWork.Product.GetAll(x => x.CategoryId == categoryId, includeProperties: "Category,ProductImages").Count(),
					ItemsPerPage = PageSize,
					CurrentPage = productpage,
				}
			};
			ViewBag.CategoryId = categoryId;
			ViewBag.Category = _unitOfWork.Category.Get(x => x.Id == categoryId).Name;
			return View(productVM);
		}

		[HttpPost]
		public IActionResult GetFilters(int categoryId,string sort)
		{
			var categories = _unitOfWork.Category.GetAll().ToList();
			var products = _unitOfWork.Product.GetAll(x => x.CategoryId == categoryId, includeProperties: "Category,ProductImages");
		
			switch (sort)
			{
				case "lowtohigh":
					{
						products = products.OrderBy(x => x.Price).ToList();
						break;
					}
				case "hightolow":
					{
						products = products.OrderByDescending(x => x.Price).ToList();
						break;
					}
				case "az":
					{
						products = products.OrderBy(x => x.Name).ToList();
						break;
					}
				default:
					{
						products = products.ToList();
						break;
					}
			}
			return PartialView("_ProductList", products);
		}
	}
}

WebQuanAn/Controllers/OrderController.cs
using WebQuanAn.DataAccess.Repository.IRepository;
using WebQuanAn.Models;
using WebQuanAn.Models.ViewModels;
using WebQuanAn.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace WebQuanAn.Controllers
{
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int orderId)
        {
            OrderVM orderVM = new()
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(x => x.Id == orderId, includeProperties: "ApplicationUser"),
                OrderDetail = _unitOfWork.OrderDetail.GetAll(x => x.OrderHeaderId == orderId, includeProperties: "Product")
            };
            return View(orderVM);
        }
        #region API CALL
        public IActionResult GetAll(string status)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var userId = Guid.Parse(claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value);

            IEnumerable<OrderHeader> order = _unitOfWork.OrderHeader
                .GetAll(x=>x.ApplicationUserId == userId, includeProperties: "ApplicationUser");

            switch (status)
            {
                case "pending":
                    order = order.Where(u => u.OrderStatus == SD.StatusPending);
                    break;
                case "approved":
                    order = order.Where(u => u.OrderStatus == SD.StatusApproved);
                    break;
                case "intransit":
                    order = order.Where(u => u.OrderStatus == SD.StatusInTransit);
                    break;
                case "shipped":
                    order = order.Where(u => u.OrderStatus == SD.StatusShipped);
                    break;
                case "cancelled":
                    order = order.Where(u => u.OrderStatus == SD.StatusCancelled);
                    break;
                default:
                    break;
            }


            return Json(new { data = order });
        }
        #endregion
    }
}

WebQuanAn/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>ADMIN-FOOTBALL</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/admin-site/assets/images/logo/favicon.png">

    <!-- page css -->

    <!-- Core css -->
    <link href="~/admin-site/assets/css/app.min.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <link href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
</head>

<body>
    <div class="app">
        <div class="layout">
            <!-- Header START -->
            <div class="header">
                <div class="logo logo-dark">
                    <a href="index.html">
                        <img src="~/admin-site/assets/images/logo/logo.png" alt="Logo">
                        <img class="logo-fold" src="assets/images/logo/logo-fold.png" alt="Logo">
                    </a>
                </div>
                <div class="logo logo-white">
                    <a href="index.html">
                        <img src="assets/images/logo/logo-white.png" alt="Logo">
                        <img class="logo-fold" src="assets/images/logo/logo-fold-white.png" alt="Logo">
                    </a>
                </div>
                <div class="nav-wrap">
                    <ul class="nav-left">

                    </ul>
                    <ul class="nav-right">
                        <li class="dropdown dropdown-animated scale-left">
               
                        </li>
                        <li class="dropdown dropdown-animated scale-left">
                            <div class="pointer" data-toggle="dropdown">                                                          
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <span>Hi, ADMIN</span>
                                }                                         
                            </div>
                            <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                    <div class="d-flex m-r-50">
                                        <div class="avatar avatar-lg avatar-image">
                                            <img src="assets/images/avatars/thumb-3.jpg" alt="">
                                        </div>
                                        <div class="m-l-10">
                                            <p class="m-b-0 text-dark font-weight-semibold">Marshall Nichols</p>
                                            <p class="m-b-0 opacity-07">UI/UX Desinger</p>
                                        </div>
                                    </div>
                                </div>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                            <span class="m-l-10">Edit Profile</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-lock"></i>
                                            <span class="m-l-10">Account Setting</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-project"></i>
                                            <span class="m-l-10">Projects</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                                <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <div>
                                            <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                            <span class="m-l-10">Logout</span>
                                        </div>
                                        <i class="anticon font-size-10 anticon-right"></i>
                                    </div>
                                </a>
                            </div>
                        </li>
                        <li>
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#quick-view">
                                <i class="anticon anticon-appstore"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>    
            <!-- Header END -->

            <!-- Side Nav START -->
            <div class="side-nav">
                <div class="side-nav-inner">
                    <ul class="side-nav-menu scrollable">

                        <li class="nav-item dropdown open">
                            <a class="dropdown-toggle" asp-action="Index" asp-controller="Dashboard" asp-area="Admin">
                                <span class="icon-holder">
                                    <i class="anticon anticon-dashboard"></i>
                                </span>
                                <span class="title">Dashboard</span>                       
                            </a> 
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle" asp-action="Index" asp-controller="Category" asp-area="Admin">
                                <span class="icon-holder">
                                    <i class="anticon anticon-appstore"></i>
                                </span>
                                <span class="title">Quán lý danh mục</span>             
                            </a>                                         
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle" asp-action="Index" asp-controller="Product" asp-area="Admin">
                                <span class="icon-holder">
                                    <i class="anticon anticon-appstore"></i>
                                </span>
                                <span class="title">Quán lý sản phẩm</span>                
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle" asp-action="Index" asp-controller="Order" asp-area="Admin">
                                <span class="icon-holder">
                                    <i class="anticon anticon-appstore"></i>
                                </span>
                                <span class="title">Quán lý đơn hàng</span>
                     
                            </a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle">
                                <span class="icon-holder">
                                    <i class="anticon anticon-build"></i>
                                </span>
                                <span class="title">Quản lý phân quyền</span>
                                <span class="arrow">
                                    <i class="arrow-icon"></i>
                                </span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a asp-action="Create" asp-controller="Role" asp-area="Admin">Tạo phân quyền</a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="Role" asp-area="Admin">Danh sách phân quyền</a>
                                </li>
                                
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle">
                                <span class="icon-holder">
									<i class="anticon anticon-build"></i>
								</span>
                                <span class="title">Quản lý người dùng</span>
                                <span class="arrow">
									<i class="arrow-icon"></i>
								</span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a asp-action="Register" asp-controller="Account" asp-area="Admin">Tạo tài khoản</a>
                                </li>
                                <li>
                                    <a asp-action="Index" asp-controller="User" asp-area="Admin">Danh sách người dùng</a>
                                </li>                
                            </ul>
                        </li>
                        <hr />
                        <li class="nav-item dropdown">
                            <a class="dropdown-toggle" href="javascript:void(0);">
                                <span class="icon-holder">
                                    <i class="anticon anticon-lock"></i>
                                </span>
                                <span class="title">Đăng xuất</span>
                          
                            </a>          
                        </li>
                    </ul>
                </div>
            </div>
            <!-- Side Nav END -->
           
            <!-- Page Container START -->
            <div class="page-container">               
                <!-- Content Wrapper START -->
                <div>
                    <main role="main" class="pb-3">
                        <partial name="_Notification" />
                        @RenderBody()
                    </main>
                </div>
                <!-- Content Wrapper END -->

                <!-- Footer START -->
                <footer class="footer">
                    <div class="footer-content">
                        <p class="m-b-0">Copyright © 2019 Theme_Nate. All rights reserved.</p>
                        <span>
                            <a href="" class="text-gray m-r-15">Term &amp; Conditions</a>
                            <a href="" class="text-gray">Privacy &amp; Policy</a>
                        </span>
                    </div>
                </footer>
                <!-- Footer END -->

            </div>
            <!-- Page Container END -->

            <!-- Search Start-->
            <div class="modal modal-left fade search" id="search-drawer">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header justify-content-between align-items-center">
                            <h5 class="modal-title">Search</h5>
                            <button type="button" class="close" data-dismiss="modal">
                                <i class="anticon anticon-close"></i>
                            </button>
                        </div>
                        <div class="modal-body scrollable">
       
                        </div>
                    </div>
                </div>
            </div>
            <!-- Search End-->
            <!-- Quick View END -->
        </div>
    </div>

    
    <!-- Core Vendors JS -->
    <script src="~/admin-site/assets/js/vendors.min.js"></script>

    <!-- page js -->
    <script src="~/admin-site/assets/vendors/chartjs/Chart.min.js"></script>
    <script src="~/admin-site/assets/js/pages/dashboard-default.js"></script>

    <!-- Core JS -->
    <script src="~/admin-site/assets/js/app.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

WebQuanAn/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/client-site/js/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/client-site/js/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["success"]');
    </script>
}

WebQuanAn/Views/Shared/_ProductList.cshtml
@using WebQuanAn.Utility.Helpers;
@model List<Product>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="total-item col-lg-4 col-md-4 col-sm-6"> 
            <div class="product_thumb">
                @if (item.ProductImages != null && item.ProductImages.Count() > 0)
                {
                    <a asp-action="Details" asp-controller="Product" asp-route-productId="@item.Id"><img src="@item.ProductImages.FirstOrDefault().ImageUrl" class="card-img-top rounded" style="width:100px height:100px" /></a>
                }
                else
                {
                    <img src="https://placehold.co/500x600/png" class="card-img-top rounded" />
                }
                <div class="action_links">
                    <ul class="d-flex justify-content-center">
                        <li class="add_to_cart">
                            <a href="cart.html"
                                title="Thêm vào giỏ hàng">
                                <span class="pe-7s-shopbag"></span>
                            </a>
                        </li>
                        <li class="wishlist">
                            <a href="#"
                                title="Yêu thích">
                                <span class="pe-7s-like"></span>
                            </a>
                        </li>
                        <li class="quick_button">
                            <a href="#" title="Quick View"
                                data-bs-toggle="modal"
                                data-bs-target="#modal_box">
                                <span class="pe-7s-look"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <figcaption class="product_content text-center">
                <h4>@item.Name</h4>
                <div class="price_box">
                    <span class="current_price">@item.Price.ToVnd()</span>
                </div>
            </figcaption>
        </div>
    }
</div>